### ISSUE TITLE
Scywalker consistently getting stuck with 1275 jobs in queue (isoquant)

### ISSUE THREAD

**Issue by carlalembke20** [derijkp/scywalker#9]
Hello,
Great work with scywalker! We've been trying to use your pipeline to analyze a single-cell long-read seq dataset based on 10x and ONT. For three out of four samples, scywalker has worked great. However, at the moment it seems to be consistently getting stuck with 1275 jobs left in the queue. From looking at the logs, we think that the problematic step may be an IsoQuant step.

We are attempting to run this sample on a few fronts to get around this issue:
1. On a workstation using -d 6 with -threads unspecified: this has been running for ~19 days and is stuck on the following step:
   -=- Running 3851612 /data/users/clembke/LRONT_scywalker/CI_2/log_jobs/isoquant-isoquant_sc-sminimap2_splice-CI_2-MT-0-16596
   -=- in queue: 1275 jobs
   
2. Via a cluster using -d 36 -threads 8: this has been running for ~7 days and seems to be stuck on the same step:
   -=- Running 345857 /data/users/clembke/LRONT_scywalker/CI_2/log_jobs/isoquant-isoquant_sc-sminimap2_splice-CI_2-MT-0-16596
   -=- in queue: 1275 jobs

3. Recently, we've also tried to run the pipeline explicitly using one thread via the cluster (with -d 4 and -threads 1), which has now also reached this step:
   -=- Running 3064899 /data/users/clembke/LRONT_scywalker/CI_2_threads/CI_2/log_jobs/isoquant-isoquant_sc-sminimap2_splice-CI_2-MT-0-16596
   -=- Running 2468550 /data/users/clembke/LRONT_scywalker/CI_2_threads/CI_2/log_jobs/isoquant-isoquant_sc-sminimap2_splice-CI_2-14-44080831-48464670
   -=- in queue: 1275 jobs

4. And lastly, we have tried to subsample the input fastq file to the size of our next-largest dataset which ran seamlessly with scywalker (92,796,333 reads instead of the original 103,304,032 reads), and are now attempting to analyze this over the cluster with -d 36 and -threads 8. This has now also reached the same job:
   -=- Running 480089 /data/users/clembke/LRONT_scywalker/CI_2_sub/log_jobs/isoquant-isoquant_sc-sminimap2_splice-CI_2_sub-14-44080831-48464670
   -=- Running 837318 /data/users/clembke/LRONT_scywalker/CI_2_sub/log_jobs/isoquant-isoquant_sc-sminimap2_splice-CI_2_sub-MT-0-16596
   -=- Running 418698 /data/users/clembke/LRONT_scywalker/CI_2_sub/log_jobs/isoquant-isoquant_sc-sminimap2_splice-CI_2_sub-5-0-4693129
   -=- in queue: 1277 jobs

We would appreciate any input or suggestions from your side on where this issue may be coming from and how we could deal with it, and of course, we are also happy to provide any more information/perform any tests on our samples and the setup for these scywalker runs.

Kind regards,
Carla

**Comment by derijkp** [comment]
You likely did not specify organelles when making your reference: Based on the names (MT-0-16596) the problem job is trying to analyze mitochondria using isoquant. Because this is very prone to cause problems (like hanging) due to the often huge amount of reads and different transcript structure, scywalker includes a completely different analysis for organelles.
In order for this to be used properly, you should specify which are the organelles (-organelles option of scywalker_makerefdir) when creating your reference, or you can download a prepared reference (if human)

Note: You mention running on a cluster using -d 36. With this option (a number) scywalker will only run multiple jobs on the same machine. To actually distribute over different nodes using the job management system, you should use -d sge or -d slurm (depending on the job management system used on your cluster)

**Comment by carlalembke20** [comment]
Thanks for the quick reply! We had assumed that the organelle specification was optional, especially since this worked for three other samples. We'd also like to point out that we are using the zebrafish genome (we've changed the reference etc accordingly, for gtf we use only protein-coding filtered gtf). On a related note, from the log it seems that the mitochondrial reads identified by scywalker/isoquant are beginning with "MT" whereas the reference genome for zebrafish has it with "mt" (ensembl version 111 GRCz11).
To give you a full picture, we are using the following full command:

```
scywalker/scywalker-0.108.0-Linux-x86_64/scywalker_makerefdir \
    -organelles "" \ 
    LRONT_scywalker/v111_scywalker \
    reference_genomes/Ensembl/Danio_rerio/GRCz11/v111/Danio_rerio.GRCz11.dna_sm.primary_assembly.fa \
    reference_genomes/Ensembl/Danio_rerio/GRCz11/v111/Danio_rerio.GRCz11.111.filtered.gtf 

scywalker/scywalker-0.108.0-Linux-x86_64/scywalker \
    -refdir LRONT_scywalker/v111_scywalker \
    -d 6 \
    -v 2 -stack 1 \
    -sc_expectedcells 500 \
    LRONT_scywalker/CI_2
```

also thank you for the note on the cluster command, we will change this accordingly

**Comment by derijkp** [comment]
Depending on source there can indeed be some variations in case, or in having chr prepended, etc. You should check how the "chromosome" is actually named the fasta file, and change the command to something like the following (using MT here, but check in the file if this is correct)
```
scywalker/scywalker-0.108.0-Linux-x86_64/scywalker_makerefdir \
    -organelles "MT" \ 
    LRONT_scywalker/v111_scywalker \
    reference_genomes/Ensembl/Danio_rerio/GRCz11/v111/Danio_rerio.GRCz11.dna_sm.primary_assembly.fa \
    reference_genomes/Ensembl/Danio_rerio/GRCz11/v111/Danio_rerio.GRCz11.111.filtered.gtf 
```

**Comment by carlalembke20** [comment]
A quick update from our side: Our original scywalker run (without the organelle calling) just finished after about 21 days, it just needed considerably more time than our other samples for this step, but it powered through in the end.
We will still also try to finish the run with organelle calling as you suggested in order to compare the resulting files. Are you able to provide any additional insights on the specifics of scywalker's organelle calling or what we could expect with regards to the output when using the organelle calling method vs. when not setting any organelles?

**Comment by derijkp** [comment]
Handling organelles separately is not for speed only:  Their gene structure is very different from  the rest of the genome, typically showing no splicing and polycystronic transcription. Using tools like isoquant that were not developed for handling this type of data will not only result in slowdowns and crashes, but you can also expect results to be worse than organelle specific analysis. scywalker organelle calling is based on overlap with known genes (necessary because of the many polycystronic reads containing multiple genes). As such, it does not try to find new genes/isoforms, but you are not expecting to find these anyway (animal mitochondria have no spliced genes, and the entire mt genome is already fully packed with genes)
You can find more info about the algorithms in our preprint (https://www.biorxiv.org/content/10.1101/2024.02.22.581508v1.full)
